### Numpy ndarray

* ndarray creation
np.array()

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print("list1:",list1)
print("list1 type:",type(list1))

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray shape and dimension

In [3]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array type:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array type:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array type:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array type: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array type: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array type: (1, 3)


In [5]:
print('array1: {:0}D, array2: {:1}D, array3: {:2}D'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1D, array2: 2D, array3:  2D


* ndarray data type

In [6]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


* astype() for type change

In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* ndarray arithmetic using axis

In [9]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


* ndarray- arange, zeros, ones

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [11]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* ndarray- reshape()

In [12]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
# error is element number doesnt match
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

reshape() using -1

In [15]:
array1 = np.arange(10)
print(array1)

#fix column as 5 and adjust row
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print('array2:\n', array2)

#fix number of rows and adjust columns
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:

array1 = np.arange(5)

# 1D ndarray to 2D ndarray
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n",array2d_1)

# 2D ndarray to 1D nd array
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n",array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [18]:
# again, error if wrong element numbers
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [20]:
# only use one -1
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

### ndarray (Indexing)

**one element at specific index**

In [21]:

array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index starts from 0
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [23]:
print('last element:',array1[-1], ', second to last element:',array1[-2])

last element: 9 , second to last element: 8


In [24]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [25]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index value:', array2d[0,0] )
print('(row=0,col=1) index value:', array2d[0,1] )
print('(row=1,col=0) index value:', array2d[1,0] )
print('(row=2,col=2) index value:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index value: 1
(row=0,col=1) index value: 2
(row=1,col=0) index value: 4
(row=2,col=2) index value: 9


**Slicing**

In [26]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [27]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


** fancy indexing **

In [29]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


** Boolean indexing **

In [30]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [31]:
print(array1d > 5)

var1 = array1d > 5
print("var1:",var1)
print(type(var1))

[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [32]:
# [ ] array1d > 5 Boolean indexing 
print(array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 boolean indexing value :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 boolean indexing value : [6 7 8 9]


In [33]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('boolean index filtering :', array3)

boolean index filtering : [6 7 8 9]


In [34]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('regular index filtering :',array4)

regular index filtering : [6 7 8 9]


In [35]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [36]:
print(array1d[array1 > 5])

[6 7 8 9]


### sort( ) and argsort( )

* list sort

In [37]:
org_array = np.array([ 3, 1, 9, 5]) 
print('original list:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) output:', sort_array1) 
print('original array after np.sort( ) :', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) output:', sort_array2)
print('original array after  org_array.sort( ):', org_array)


original list: [3 1 9 5]
np.sort( ) output: [1 3 5 9]
original array after np.sort( ) : [3 1 9 5]
org_array.sort( ) output: None
original array after  org_array.sort( ): [1 3 5 9]


In [38]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('descending order:', sort_array1_desc) 

descending order: [9 5 3 1]


In [39]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('sort by row:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('sort by column:\n', sort_array2d_axis1)

sort by row:
 [[ 7  1]
 [ 8 12]]
sort by column:
 [[ 8 12]
 [ 1  7]]


* argsort

In [40]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('original list after argsort:', sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
original list after argsort: [1 0 3 2]


In [41]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('original list after argsort:', sort_indices_desc)

[9 5 3 1]
original list after argsort: [2 3 0 1]


key-value data with John=78, Mike=95, Sarah=84, Kate=98, Samuel=88
use argsort() to sort key

In [43]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)


sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


### Dot product and transpose

* Dot product

In [44]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('dot product:\n', dot_product)

dot product:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [45]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A Transpose:\n', transpose_mat)

A Transpose:
 [[1 3]
 [2 4]]
