### Data encoding

* Label encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

items=['TV','Fridge','Microwave','Computer','Fan','Fan','sofa','sofa']

# LabelEncoder class and use fit( ) & transform( ) for label encoding 
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('encoded values:',labels)

encoded values: [4 2 3 0 1 1 5 5]


In [2]:
print('encoder class:',encoder.classes_)

encoder class: ['Computer' 'Fan' 'Fridge' 'Microwave' 'TV' 'sofa']


In [3]:
print('decode values:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

decode values: ['TV' 'sofa' 'Fridge' 'Computer' 'Fan' 'Fan' 'Microwave' 'Microwave']


* One-Hot encoding

In [4]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','Fridge','Microwave','Computer','Fan','Fan','sofa','sofa']

# use LabelEncoder to encode into numeric values
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# reshape into 2D array
labels = labels.reshape(-1,1)

# apply one-hot encoding 
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('one-hot encoded data')
print(oh_labels.toarray())
print('one-hot encoded data shape')
print(oh_labels.shape)

one-hot encoded data
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
one-hot encoded data shape
(8, 6)


In [5]:
import pandas as pd

df = pd.DataFrame({'item':['TV','Fridge','Microwave','Computer','Fan','Fan','sofa','sofa'] })
df

item
0         TV
1     Fridge
2  Microwave
3   Computer
4        Fan
5        Fan
6       sofa
7       sofa

In [6]:
pd.get_dummies(df)

item_Computer  item_Fan  item_Fridge  item_Microwave  item_TV  item_sofa
0              0         0            0               0        1          0
1              0         0            1               0        0          0
2              0         0            0               1        0          0
3              1         0            0               0        0          0
4              0         1            0               0        0          0
5              0         1            0               0        0          0
6              0         0            0               0        0          1
7              0         0            0               0        0          1

### Feature scaling and normalization

* StandardScaler

In [8]:
from sklearn.datasets import load_iris
import pandas as pd
# load iris dataset and convert to dataframe
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('average value of features')
print(iris_df.mean())
print('\nfeature variance')
print(iris_df.var())


average value of features
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature variance
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [9]:
from sklearn.preprocessing import StandardScaler

# StandardScaler class
scaler = StandardScaler()
# StandardScaler and use fit( ) & transform( )
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform into dataframe
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('average value of features')
print(iris_df_scaled.mean())
print('\nfeature variance')
print(iris_df_scaled.var())

average value of features
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature variance
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* MinMaxScaler

In [10]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler class
scaler = MinMaxScaler()
# MinMaxScaler, use fit() & transform().  
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# convert to dataframe
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('min value of each feature')
print(iris_df_scaled.min())
print('\nmax value of each feature')
print(iris_df_scaled.max())


min value of each feature
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

max value of each feature
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
