In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', 'Fridge', 'Microwave', 'Computer', 'Fan', 'Fan', 'Mixer', 'Mixer']

#LabelEncoder class => fit() => transform()
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [2]:
print(labels)
encoder.classes_

[5 2 3 0 1 1 4 4]


array(['Computer', 'Fan', 'Fridge', 'Microwave', 'Mixer', 'TV'],
      dtype='<U9')

In [3]:
encoder.inverse_transform(labels)

array(['TV', 'Fridge', 'Microwave', 'Computer', 'Fan', 'Fan', 'Mixer',
       'Mixer'], dtype='<U9')

In [9]:
# one hot
# 2d data transform then do one hot encoding

from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]


C:\Users\DooDoo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [10]:
type(oh_labels)

scipy.sparse.csr.csr_matrix

In [12]:
df = pd.DataFrame({'item' : ['TV', 'Fridge', 'Microwave', 'Computer', 'Fan', 'Fan', 'Mixer', 'Mixer']})
pd.get_dummies(df)

item_Computer  item_Fan  item_Fridge  item_Microwave  item_Mixer  item_TV
0              0         0            0               0           0        1
1              0         0            1               0           0        0
2              0         0            0               1           0        0
3              1         0            0               0           0        0
4              0         1            0               0           0        0
5              0         1            0               0           0        0
6              0         0            0               0           1        0
7              0         0            0               0           1        0

In [13]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

In [15]:
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

In [19]:
print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
